version: '3.7'

services:
  # Blockchain
  evm_l2_node:
    container_name: besu_l2
    hostname: template_test_node
    image: hyperledger/besu:latest
    user: "root:root"
    restart: unless-stopped

    ports:
      - "${RPC_HTTP_PORT:-9555}:9555"     # HTTP RPC L2
      - "${RPC_WS_PORT:-9556}:9556"     # WS RPC L2
      - "31303:30303"   # P2P TCP
      - "31303:30303/udp" # P2P UDP

    volumes:
      - ./data:/opt/besu/database
      - ./networkFiles/config:/etc/besu/config
      - ./networkFiles/keys/bootnode:/etc/besu/keys
    
    environment:
      - BESU_USER_NAME=root

    command: >
      --data-path=/opt/besu/database
      --genesis-file=/etc/besu/config/genesis.json
      --node-private-key-file=/etc/besu/keys/key
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=9555
      --rpc-http-cors-origins="*"
      --rpc-http-api=ADMIN,CLIQUE,DEBUG,ETH,NET,TRACE,TXPOOL,WEB3
      --rpc-http-authentication-enabled=false
      --rpc-http-max-active-connections=1000
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=9556
      --rpc-ws-api=ADMIN,CLIQUE,DEBUG,ETH,NET,TRACE,TXPOOL,WEB3
      --min-gas-price=0
      --miner-enabled
      --miner-coinbase=0xb6c94f0eB270839e07b693D17E7a757DD7223618
      --host-allowlist="*"
      --p2p-host=0.0.0.0
      --nat-method=NONE
      --logging=${LOG_LEVEL:-INFO}
