-- PostgreSQL setup script
-- Run this script to set up the database schema and indexes
-- Warning: This file is automatically generated, do not modify it.

CREATE TABLE "contract_event_status" (
    "address" VARCHAR(255) PRIMARY KEY,
    "first_event" BIGINT,
    "last_sync_event" BIGINT
);

CREATE TABLE "dynamic_configuration" (
    "config_key" VARCHAR(255) PRIMARY KEY,
    "config_value" MEDIUMTEXT
);

CREATE TABLE "event_example_asset_modified" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_asset_id" TEXT,
    "p_new_title" TEXT,
    "p_timestamp" VARCHAR(255)
);

CREATE INDEX "ix_event_example_asset_modified_s_1" ON "event_example_asset_modified"("id" DESC);
CREATE INDEX "ix_event_example_asset_modified_s_2" ON "event_example_asset_modified"("block");
CREATE INDEX "ix_event_example_asset_modified_s_3" ON "event_example_asset_modified"("tx");

CREATE TABLE "event_example_asset_registered" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_owner" VARCHAR(255),
    "p_asset_id" TEXT,
    "p_timestamp" VARCHAR(255),
    "p_title" TEXT
);

CREATE INDEX "ix_event_example_asset_registered_s_1" ON "event_example_asset_registered"("id" DESC);
CREATE INDEX "ix_event_example_asset_registered_s_2" ON "event_example_asset_registered"("block");
CREATE INDEX "ix_event_example_asset_registered_s_3" ON "event_example_asset_registered"("tx");
CREATE INDEX "ix_event_example_asset_registered_s_4" ON "event_example_asset_registered"("p_owner", "id" DESC);

CREATE TABLE "event_example_initialized" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_version" VARCHAR(255)
);

CREATE INDEX "ix_event_example_initialized_s_1" ON "event_example_initialized"("id" DESC);
CREATE INDEX "ix_event_example_initialized_s_2" ON "event_example_initialized"("block");
CREATE INDEX "ix_event_example_initialized_s_3" ON "event_example_initialized"("tx");

CREATE TABLE "event_example_paused" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_example_paused_s_1" ON "event_example_paused"("id" DESC);
CREATE INDEX "ix_event_example_paused_s_2" ON "event_example_paused"("block");
CREATE INDEX "ix_event_example_paused_s_3" ON "event_example_paused"("tx");

CREATE TABLE "event_example_unpaused" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_example_unpaused_s_1" ON "event_example_unpaused"("id" DESC);
CREATE INDEX "ix_event_example_unpaused_s_2" ON "event_example_unpaused"("block");
CREATE INDEX "ix_event_example_unpaused_s_3" ON "event_example_unpaused"("tx");

CREATE TABLE "event_example_upgraded" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_implementation" VARCHAR(255)
);

CREATE INDEX "ix_event_example_upgraded_s_1" ON "event_example_upgraded"("id" DESC);
CREATE INDEX "ix_event_example_upgraded_s_2" ON "event_example_upgraded"("block");
CREATE INDEX "ix_event_example_upgraded_s_3" ON "event_example_upgraded"("tx");
CREATE INDEX "ix_event_example_upgraded_s_4" ON "event_example_upgraded"("p_implementation", "id" DESC);

CREATE TABLE "event_role_manager_initialized" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_version" VARCHAR(255)
);

CREATE INDEX "ix_event_role_manager_initialized_s_1" ON "event_role_manager_initialized"("id" DESC);
CREATE INDEX "ix_event_role_manager_initialized_s_2" ON "event_role_manager_initialized"("block");
CREATE INDEX "ix_event_role_manager_initialized_s_3" ON "event_role_manager_initialized"("tx");

CREATE TABLE "event_role_manager_paused" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_role_manager_paused_s_1" ON "event_role_manager_paused"("id" DESC);
CREATE INDEX "ix_event_role_manager_paused_s_2" ON "event_role_manager_paused"("block");
CREATE INDEX "ix_event_role_manager_paused_s_3" ON "event_role_manager_paused"("tx");

CREATE TABLE "event_role_manager_role_assigned" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_account" VARCHAR(255),
    "p_role" VARCHAR(255),
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_role_manager_role_assigned_s_1" ON "event_role_manager_role_assigned"("id" DESC);
CREATE INDEX "ix_event_role_manager_role_assigned_s_2" ON "event_role_manager_role_assigned"("block");
CREATE INDEX "ix_event_role_manager_role_assigned_s_3" ON "event_role_manager_role_assigned"("tx");

CREATE TABLE "event_role_manager_role_revoked" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_account" VARCHAR(255),
    "p_role" VARCHAR(255),
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_role_manager_role_revoked_s_1" ON "event_role_manager_role_revoked"("id" DESC);
CREATE INDEX "ix_event_role_manager_role_revoked_s_2" ON "event_role_manager_role_revoked"("block");
CREATE INDEX "ix_event_role_manager_role_revoked_s_3" ON "event_role_manager_role_revoked"("tx");

CREATE TABLE "event_role_manager_unpaused" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_role_manager_unpaused_s_1" ON "event_role_manager_unpaused"("id" DESC);
CREATE INDEX "ix_event_role_manager_unpaused_s_2" ON "event_role_manager_unpaused"("block");
CREATE INDEX "ix_event_role_manager_unpaused_s_3" ON "event_role_manager_unpaused"("tx");

CREATE TABLE "event_role_manager_upgraded" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_implementation" VARCHAR(255)
);

CREATE INDEX "ix_event_role_manager_upgraded_s_1" ON "event_role_manager_upgraded"("id" DESC);
CREATE INDEX "ix_event_role_manager_upgraded_s_2" ON "event_role_manager_upgraded"("block");
CREATE INDEX "ix_event_role_manager_upgraded_s_3" ON "event_role_manager_upgraded"("tx");
CREATE INDEX "ix_event_role_manager_upgraded_s_4" ON "event_role_manager_upgraded"("p_implementation", "id" DESC);

CREATE TABLE "event_upgrade_control_contract_upgraded" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_proxy" VARCHAR(255),
    "p_implementation" VARCHAR(255),
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_upgrade_control_contract_upgraded_s_1" ON "event_upgrade_control_contract_upgraded"("id" DESC);
CREATE INDEX "ix_event_upgrade_control_contract_upgraded_s_2" ON "event_upgrade_control_contract_upgraded"("block");
CREATE INDEX "ix_event_upgrade_control_contract_upgraded_s_3" ON "event_upgrade_control_contract_upgraded"("tx");

CREATE TABLE "event_upgrade_control_initialized" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_version" VARCHAR(255)
);

CREATE INDEX "ix_event_upgrade_control_initialized_s_1" ON "event_upgrade_control_initialized"("id" DESC);
CREATE INDEX "ix_event_upgrade_control_initialized_s_2" ON "event_upgrade_control_initialized"("block");
CREATE INDEX "ix_event_upgrade_control_initialized_s_3" ON "event_upgrade_control_initialized"("tx");

CREATE TABLE "event_upgrade_control_paused" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_upgrade_control_paused_s_1" ON "event_upgrade_control_paused"("id" DESC);
CREATE INDEX "ix_event_upgrade_control_paused_s_2" ON "event_upgrade_control_paused"("block");
CREATE INDEX "ix_event_upgrade_control_paused_s_3" ON "event_upgrade_control_paused"("tx");

CREATE TABLE "event_upgrade_control_unpaused" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_by" VARCHAR(255)
);

CREATE INDEX "ix_event_upgrade_control_unpaused_s_1" ON "event_upgrade_control_unpaused"("id" DESC);
CREATE INDEX "ix_event_upgrade_control_unpaused_s_2" ON "event_upgrade_control_unpaused"("block");
CREATE INDEX "ix_event_upgrade_control_unpaused_s_3" ON "event_upgrade_control_unpaused"("tx");

CREATE TABLE "event_upgrade_control_upgraded" (
    "id" VARCHAR(255) PRIMARY KEY,
    "block" BIGINT,
    "event_index" BIGINT,
    "tx" VARCHAR(255),
    "timestamp" BIGINT,
    "p_implementation" VARCHAR(255)
);

CREATE INDEX "ix_event_upgrade_control_upgraded_s_1" ON "event_upgrade_control_upgraded"("id" DESC);
CREATE INDEX "ix_event_upgrade_control_upgraded_s_2" ON "event_upgrade_control_upgraded"("block");
CREATE INDEX "ix_event_upgrade_control_upgraded_s_3" ON "event_upgrade_control_upgraded"("tx");
CREATE INDEX "ix_event_upgrade_control_upgraded_s_4" ON "event_upgrade_control_upgraded"("p_implementation", "id" DESC);

CREATE TABLE "wallets" (
    "id" VARCHAR(255) PRIMARY KEY,
    "uid" VARCHAR(255),
    "name" VARCHAR(255),
    "address" VARCHAR(255),
    "encrypted_key" TEXT,
    "password_hash" VARCHAR(255),
    "password_salt" VARCHAR(255)
);

CREATE INDEX "ix_wallets_s_1" ON "wallets"("uid");
