version: "3.9"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"   # API S3
      - "9090:9090"   # Console web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    volumes:
      - minio_data:/data  # persist storage

volumes:
  minio_data: